baseurl = "http://dan.donoghue.eu"
languageCode = "en-gb"
title = "Dan Donoghue"
theme = "dandonoghue"
publishDir = "docs"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    tabWidth = 4
